
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

jobs:
  - job: CPU_MXNET_1_8_0
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: MXNET_VERSION=1.8.0 make docker_build_cpu
        workingDirectory: dockerfiles
      - script: MXNET_VERSION=1.8.0 ./push.sh docker_push_cpu
        workingDirectory: dockerfiles
        condition: eq(variables.isMain, true)
  - job: GPU_MXNET_1_8_0_CUDA100
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=10.0 make docker_build_gpu
        workingDirectory: dockerfiles
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=10.0 ./push.sh docker_push_gpu
        workingDirectory: dockerfiles
        condition: eq(variables.isMain, true)
  - job: GPU_MXNET_1_8_0_CUDA101
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=10.1 make docker_build_gpu
        workingDirectory: dockerfiles
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=10.1 ./push.sh docker_push_gpu
        workingDirectory: dockerfiles
        condition: eq(variables.isMain, true)
  - job: GPU_MXNET_1_8_0_CUDA102
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=10.2 make docker_build_gpu
        workingDirectory: dockerfiles
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=10.2 ./push.sh docker_push_gpu
        workingDirectory: dockerfiles
        condition: eq(variables.isMain, true)
  - job: GPU_MXNET_1_8_0_CUDA110
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=11.0 make docker_build_gpu
        workingDirectory: dockerfiles
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=11.0 ./push.sh docker_push_gpu
        workingDirectory: dockerfiles
        condition: eq(variables.isMain, true)
  - job: GPU_MXNET_1_8_0_CUDA111
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=11.1 make docker_build_gpu
        workingDirectory: dockerfiles
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=11.1 ./push.sh docker_push_gpu
        workingDirectory: dockerfiles
        condition: eq(variables.isMain, true)
  - job: GPU_MXNET_1_8_0_CUDA112
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=11.2 make docker_build_gpu
        workingDirectory: dockerfiles
      - script: MXNET_VERSION=1.8.0 CUDA_VERSION=11.2 ./push.sh docker_push_gpu
        workingDirectory: dockerfiles
        condition: eq(variables.isMain, true)
